force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city in which the leased property is located.</description>
    <inlineHelpText>The city in which the leased property is located.</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The US state in which the leased property is located.</description>
    <inlineHelpText>The US state in which the leased property is located.</inlineHelpText>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>US_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>The street address of the leased property.</description>
    <inlineHelpText>The street address of the leased property.</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The Zip or postal code in which the leased property is located.</description>
    <inlineHelpText>The Zip or postal code in which the leased property is located.</inlineHelpText>
    <label>Zip Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/Property_Vendor__c.object-meta.xml
<CustomObject>
    <label>Property Vendor</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>Property Vendor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Vendor__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/fields/Expired_Contract__c.field-meta.xml
<CustomField>
    <fullName>Expired_Contract__c</fullName>
    <description>Indicates whether or not the contract with the vendor has expired.</description>
    <formula>NOT (AND(
  TODAY() &gt;= Contract_Start_Date__c,
  TODAY() &lt;= Contract_End_Date__c
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether or not the contract with the vendor has expired.</inlineHelpText>
    <label>Expired Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/fields/Preferred_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Vendor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Preferred Vendor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Vendors</relationshipLabel>
    <relationshipName>Property_Vendors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Facility Services</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>IT Support</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_Vendor__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Property Vendors</relationshipLabel>
    <relationshipName>Property_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/US_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>NJ</fullName>
    </customValue>
    <description>US states and territories 2-letter codes.</description>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QueryPropertyVendorsAction.cls
public with sharing class QueryPropertyVendorsAction { 

    /**
     * Request wrapper
     */
    public class Request {
        @InvocableVariable(label='Property' description='Property__c record to find vendors for' required=true)
        public Property__c Property;
    }
    
    /**
     * Response wrapper
     */
    public class Response {
        @InvocableVariable(label='Prompt' description='List of Property_Vendor__c records with vendor details')
        public List<Property_Vendor__c> Prompt;
    }

    @InvocableMethod(label='Query Property Vendors' description='Retrieves Property_Vendor__c records for properties to ground Agentforce responses')
    public static List<Response> getPropertyVendorsForGrounding(List<Request> requests) {

        List<Response> responses = new List<Response>();
        
        for (Request request : requests) {
            Response response = new Response();
            
            if (request.Property == null) {
                response.Prompt = new List<Property_Vendor__c>();
                responses.add(response);
                continue;
            }
            
            // Query for all Property_Vendor__c records for the property with active contracts
            List<Property_Vendor__c> propertyVendors = [
                SELECT Id, Property__c, Property__r.Name, Property__r.Street__c, 
                       Property__r.City__c, Property__r.State__c, Property__r.Zip_Code__c, 
                       Vendor__c, Service_Type__c, Contract_Start_Date__c, Contract_End_Date__c, Expired_Contract__c,
                       Preferred_Vendor__c, Emergency_Contact__c, Notes__c, 
                       Vendor__r.Id, Vendor__r.Name, Vendor__r.Type, Vendor__r.Phone, 
                       Vendor__r.Website, Vendor__r.BillingStreet, Vendor__r.BillingCity, 
                       Vendor__r.BillingState, Vendor__r.BillingPostalCode, 
                       Vendor__r.BillingCountry, Vendor__r.Description, 
                       Vendor__r.SicDesc, Vendor__r.Sic 
                FROM Property_Vendor__c 
                WHERE Property__c = :request.Property.Id 
                AND Expired_Contract__c = FALSE
                ORDER BY Preferred_Vendor__c DESC, Vendor__r.Name
            ];
            
            response.Prompt = propertyVendors;
            responses.add(response);
        }
        
        return responses;
    }
}